comment_width = 100
condense_wildcard_suffixes = true
edition = "2024"
enum_discrim_align_threshold = 20
fn_single_line = true
force_multiline_blocks = true
format_code_in_doc_comments = true
format_macro_matchers = true
format_strings = true
imports_indent = "Visual"
imports_layout = "HorizontalVertical"
#indent_style = "Visual"
inline_attribute_width = 50
match_block_trailing_comma = true
imports_granularity = "Crate"
normalize_comments = true
normalize_doc_attributes = true
overflow_delimited_expr = true
remove_nested_parens = true
reorder_impl_items = true
group_imports = "StdExternalCrate"
short_array_element_width_threshold = 15
struct_field_align_threshold = 5
style_edition = "2024"
unstable_features = true
use_field_init_shorthand = true
use_small_heuristics = "Max"
use_try_shorthand = true
where_single_line = true
wrap_comments = true
